### ISSUE TITLE
FIX | `require('fs')` (so, this plugin) breaks on latest Node version

### ISSUE THREAD

**Issue by ChasKane** [pjeby/hot-reload#16]
After upgrading to latest `node` version (v20.16.0), I started seeing the below error in the console and noticed that hot reload wasn't working anymore (changes to other plugins' `main.js` files didn't work). I'm not sure what change in `node` made this happen, but adding `window.` before `require("fs")` fixed it for me. Leaving the this and [the reference](https://stackoverflow.com/questions/35428639/how-can-i-use-fs-in-react-with-electron?rq=4) in case this is helpful for anyone else. As I'm unsure if this is a shared issue, I'll abstain from making a fork and PR for now.

`Error: [hot-reload] Attempting to load NodeJS package: "fs"`

**Comment by pjeby** [comment]
I don't understand how your node upgrade could remotely be relevant, since Obsidian is in Electron and neither it nor hot-reload use your local node installation in any fashion.  Did you recently upgrade Obsidian, perhaps?  Especially an upgrade via the installer?

**Comment by pjeby** [comment]
Actually, given the PR, does that mean that this issue was you trying to use the plugin on mobile?  If so, please go ahead and close this.
