### ISSUE TITLE
Not detecting change when copying files into vault

### ISSUE THREAD

**Issue by yankeeinlondon** [pjeby/hot-reload#17]
I am using iCloud to sync my vault across devices and I was finding that certain files in the `node_modules` directory were not able to sync so I needed an alternative to working directly on my plugin inside the vault.

What I do now is, every time I build the repo (which lives externally to the vault), I then have a script copy over the `main.js`, `manifest.json`, and `styles.css` to the `[VAULT]/.obsidian/plugins/[PLUGIN NAME]` directory.

My script does update the filesand if I stop and restart Obsidian I get the new version but for some reason the change is not detected. I tried adding a `touch "${filename}"` but this didn't change the outcome.

**Comment by pjeby** [comment]
Did you remember to add a `.hotreload` file?

**Comment by yankeeinlondon** [comment]
Well actually I did not at first but having added it I could have sworn it still didn't work (and hence the issue) but I must admit that sometime last night it did start working. Maybe it was the introduction of that file. I'll close this issue though as I think my situation has now become hard to reproduce. :)
