### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emilio-toledo** [pjeby/hot-reload#5]
Hey @pjeby thanks for such an amazing plugin. I am using for my [obsidian-svelte-plugin](https://github.com/emilio-toledo/obsidian-svelte-plugin) template and [obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview) also uses it. It just crossed my mind that hot-reload doesn't have a license yet, do you mind adding one to prevent a misunderstandings in the future?

**Comment by pjeby** [comment]
Done.
